import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "@/styles/globals.css";

const coreFont = Merriweather_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={coreFont.className}>{children}</body>
    </html>
  );
}
